(FILEGROWTH = 43152KB)

USE[REVISAO]
GO

CREATE TABLE [MÃE]
([CPF] VARCHAR(11) NOT NULL,
 [NOME] VARCHAR(150) NOT NULL,
 [ENDERECO] VARCHAR(200) NULL,
 [TELEFONE] VARCHAR(15) NULL,
 [DATA NASCIMENTO] DATE NULL,
--CHAVE PRIMARIA
CONSTRAINT[PK MÃE]
	PRIMARY KEY([CPF]))
	